name: mlflow-ci-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - pip
  - scikit-learn=1.0.2
  - pandas=1.4.2
  - mlflow=1.25.1
  - setuptools=58.2.0  
  - wheel              
  - pip:
    - numpy
    - scipy